# Bitcoin Sprint Enterprise Storage Validation Service Configuration
# Production-ready configuration for paid storage validation service

[server]
host = "0.0.0.0"
port = 8443
workers = 8
max_connections = 10000
keep_alive = 75

[security]
tls_enabled = true
tls_cert_path = "certs/server.crt"
tls_key_path = "certs/server.key"
api_key_required = true
rate_limiting_enabled = true
circuit_breaker_enabled = true

[storage_validation]
enabled = true
supported_protocols = ["ipfs", "filecoin", "arweave", "custom"]
default_protocol = "ipfs"
max_file_size_mb = 100
verification_timeout_seconds = 30
merkle_proof_required = false

[redis]
enabled = true
url = "redis://localhost:6379"
rate_limit_window_seconds = 60
max_requests_per_window = 100

[monitoring]
prometheus_enabled = true
prometheus_port = 9090
metrics_enabled = true
health_check_interval_seconds = 30

[subscriptions]
# Free tier
free_credits_per_month = 100
free_max_concurrent = 1

# Developer tier
developer_credits_per_month = 1000
developer_max_concurrent = 5

# Professional tier
professional_credits_per_month = 50000
professional_max_concurrent = 20

# Enterprise tier
enterprise_credits_per_month = 999999999  # Unlimited
enterprise_max_concurrent = 100

[protocols]
supported_protocols = ["ipfs", "filecoin", "arweave", "custom"]
default_protocol = "ipfs"
custom_protocols_allowed = true

[verification]
max_file_size_bytes = 1073741824  # 1GB
verification_timeout_seconds = 30
parallel_verifications = 10
challenge_expiry_seconds = 300

[webhooks]
enabled = true
max_retries = 3
retry_delay_seconds = 5
timeout_seconds = 10

[analytics]
enabled = true
retention_days = 90
real_time_updates = true
export_formats = ["json", "csv", "pdf"]

[logging]
level = "INFO"
format = "json"
file_path = "logs/enterprise-server.log"
max_file_size_mb = 100
max_files = 10

[database]
# For production, use PostgreSQL or similar
type = "sqlite"
path = "data/enterprise.db"
connection_pool_size = 10
migrations_enabled = true

[stripe]
enabled = true
publishable_key = "pk_test_your_stripe_publishable_key"
secret_key = "sk_test_your_stripe_secret_key"
webhook_secret = "whsec_your_webhook_secret"

[features]
ai_insights = true
predictive_analytics = true
anomaly_detection = true
custom_integrations = true
white_label = true
